import sys

def main():
    with open('www/index.html', 'r', encoding='utf-8') as f:
        html = f.read()

    # 1. CSS Injection
    css_to_replace = """    .tab-content {
      display: none;
      animation: fadeIn 0.35s cubic-bezier(0.4, 0, 0.2, 1);
    }
    .tab-content.active {
      display: block;
    }

    @keyframes fadeIn {
      from { opacity: 0; transform: translateY(12px); }
      to { opacity: 1; transform: translateY(0); }
    }"""
    
    new_css = """    .tab-content {
      display: none;
      /* default fallback animation */
      animation: fadeIn 0.35s cubic-bezier(0.4, 0, 0.2, 1);
    }
    .tab-content.active {
      display: block;
    }
    .tab-content.active.slide-left {
      animation: slideInLeft 0.3s cubic-bezier(0.25, 1, 0.5, 1);
    }
    .tab-content.active.slide-right {
      animation: slideInRight 0.3s cubic-bezier(0.25, 1, 0.5, 1);
    }

    @keyframes fadeIn {
      from { opacity: 0; transform: translateY(12px); }
      to { opacity: 1; transform: translateY(0); }
    }
    @keyframes slideInRight {
      from { opacity: 0; transform: translateX(30px); }
      to { opacity: 1; transform: translateX(0); }
    }
    @keyframes slideInLeft {
      from { opacity: 0; transform: translateX(-30px); }
      to { opacity: 1; transform: translateX(0); }
    }"""
    if css_to_replace in html:
        html = html.replace(css_to_replace, new_css)
        print("Replaced tab animation CSS")
    else:
        print("Could not find tab CSS")

    chart_css = """
    /* CHART STYLES */
    .chart-container {
      display: flex;
      align-items: flex-end;
      justify-content: space-between;
      height: 140px;
      margin-top: 10px;
      padding-top: 20px;
      gap: 6px;
    }
    .chart-col {
      flex: 1;
      display: flex;
      flex-direction: column;
      align-items: center;
      justify-content: flex-end;
      height: 100%;
    }
    .chart-bar-wrapper {
      width: 100%;
      height: 100%;
      display: flex;
      align-items: flex-end;
      justify-content: center;
      position: relative;
    }
    .chart-bar {
      width: 80%;
      max-width: 24px;
      background: var(--or);
      border-radius: 4px 4px 0 0;
      transition: height 0.6s cubic-bezier(0.4, 0, 0.2, 1);
      height: 0%; /* Dynamic */
    }
    .chart-label {
      font-size: 9.5px;
      color: var(--gy);
      margin-top: 6px;
      text-transform: uppercase;
      font-weight: 600;
    }
    .chart-val-tooltip {
      position: absolute;
      top: -22px;
      font-size: 9px;
      font-weight: 700;
      color: #fff;
      background: var(--bk);
      padding: 2px 6px;
      border-radius: 4px;
      border: 1px solid rgba(255,255,255,0.1);
      opacity: 0;
      transition: opacity 0.2s;
      pointer-events: none;
      white-space: nowrap;
      z-index: 5;
    }
    .chart-col:hover .chart-val-tooltip, .chart-col:active .chart-val-tooltip {
      opacity: 1;
    }
    """
    if '/* CHART STYLES */' not in html:
        html = html.replace('/* STATS GRID */', chart_css + '\n    /* STATS GRID */')
        print("Inserted chart CSS")


    # 2. HTML Injection
    html_inject = """
        <div class="card">
          <div class="card-title" data-i18n="Penjualan 7 Hari Terakhir">Penjualan 7 Hari Terakhir</div>
          <div class="chart-container" id="dashboard-chart">
            <!-- Bars will be generated by JS -->
          </div>
        </div>
"""
    if '<div class="chart-container" id="dashboard-chart">' not in html:
        html = html.replace('<div class="card">\n          <div class="card-title">Pintasan Cepat</div>', html_inject + '\n        <div class="card">\n          <div class="card-title">Pintasan Cepat</div>')
        print("Inserted chart HTML")


    # 3. JS Injection (switchTab)
    old_switch = """    function switchTab(tabId) {
      // Hide active tab content
      document.getElementById(`tab-${currentTab}`).classList.remove('active');
      const oldNav = document.getElementById(`nav-${currentTab}`);
      if (oldNav) oldNav.classList.remove('active');

      // Show new tab content
      document.getElementById(`tab-${tabId}`).classList.add('active');
      const newNav = document.getElementById(`nav-${tabId}`);
      if (newNav) newNav.classList.add('active');

      currentTab = tabId;

      // Show/hide live-banner based on tab
      const liveBanner = document.querySelector('.live-banner');
      if (liveBanner) {
        liveBanner.style.display = (tabId === 'form') ? 'flex' : 'none';
      }

      // Special triggers
      if (tabId === 'dashboard') {"""
      
    new_switch = """    const tabOrder = { 'dashboard': 0, 'history': 1, 'form': 2, 'products': 3, 'katalog': 4, 'settings': 5 };

    function switchTab(tabId) {
      const oldIndex = tabOrder[currentTab];
      const newIndex = tabOrder[tabId];
      let directionClass = 'slide-left';
      if (newIndex < oldIndex) {
        directionClass = 'slide-right';
      }

      // Hide active tab content
      const oldTab = document.getElementById(`tab-${currentTab}`);
      oldTab.classList.remove('active', 'slide-left', 'slide-right');
      const oldNav = document.getElementById(`nav-${currentTab}`);
      if (oldNav) oldNav.classList.remove('active');

      // Show new tab content
      const newTab = document.getElementById(`tab-${tabId}`);
      newTab.classList.remove('slide-left', 'slide-right');
      void newTab.offsetWidth; // trigger reflow
      newTab.classList.add('active', directionClass);
      
      const newNav = document.getElementById(`nav-${tabId}`);
      if (newNav) newNav.classList.add('active');

      currentTab = tabId;

      // Show/hide live-banner based on tab
      const liveBanner = document.querySelector('.live-banner');
      if (liveBanner) {
        liveBanner.style.display = (tabId === 'form') ? 'flex' : 'none';
      }

      // Special triggers
      if (tabId === 'dashboard') {
        renderDashboardChart();"""
    
    if 'let directionClass' not in html:
        html = html.replace(old_switch, new_switch)
        print("Replaced switchTab JS")

    
    # 4. JS Chart Function
    chart_js = """
    function renderDashboardChart() {
      const chartContainer = document.getElementById('dashboard-chart');
      if (!chartContainer) return;
      
      chartContainer.innerHTML = ''; // clear

      // Get last 7 days
      const days = [];
      const totals = [];
      let maxTotal = 0;
      
      // Initialize last 7 days
      for (let i = 6; i >= 0; i--) {
        const d = new Date();
        d.setDate(d.getDate() - i);
        const dateStr = d.toLocaleDateString('id-ID', { day: '2-digit', month: 'short' });
        
        // adjust for local timezone offset for accurate YYYY-MM-DD
        const offset = d.getTimezoneOffset() * 60000;
        const localISOTime = (new Date(d.getTime() - offset)).toISOString().split('T')[0];
        const matchDate = localISOTime;
        
        // Calculate total for this day
        let dayTotal = 0;
        transactions.forEach(t => {
           if (t.date.startsWith(matchDate) && (t.status === 'lunas' || t.status === 'dp')) {
              dayTotal += t.total;
           }
        });
        
        days.push(dateStr);
        totals.push(dayTotal);
        if (dayTotal > maxTotal) maxTotal = dayTotal;
      }
      
      // If maxTotal is 0, make it 1 so we don't divide by 0
      if (maxTotal === 0) maxTotal = 1;

      // Render bars
      for (let i = 0; i < 7; i++) {
        const percent = Math.max((totals[i] / maxTotal) * 100, 2); // min 2% so it's visible
        const formattedTotal = totals[i].toLocaleString('id-ID');
        
        const col = document.createElement('div');
        col.className = 'chart-col';
        col.innerHTML = `
          <div class="chart-bar-wrapper">
            <div class="chart-val-tooltip">Rp ${formattedTotal}</div>
            <div class="chart-bar" style="height: 0%"></div>
          </div>
          <div class="chart-label">${days[i].split(' ')[0]}</div>
        `;
        chartContainer.appendChild(col);
        
        // trigger animation
        setTimeout(() => {
          col.querySelector('.chart-bar').style.height = percent + '%';
        }, 50 + (i * 50));
      }
    }
"""
    if 'function renderDashboardChart' not in html:
        html = html.replace('function calculateDashboardStats() {', chart_js + '\n    function calculateDashboardStats() {')
        print("Inserted renderDashboardChart function")
        
    # Inject call in calculateDashboardStats
    if 'renderDashboardChart();' not in html.split('function calculateDashboardStats() {')[1]:
        html = html.replace('function calculateDashboardStats() {\n      let totalOmset = 0;', 'function calculateDashboardStats() {\n      renderDashboardChart();\n      let totalOmset = 0;')
        print("Called renderDashboardChart inside calculateDashboardStats")

    # Add translations
    if '"Penjualan 7 Hari Terakhir": "Penjualan 7 Hari Terakhir"' not in html:
        html = html.replace('"Pintasan Cepat": "Quick Shortcuts",', '"Pintasan Cepat": "Quick Shortcuts", "Penjualan 7 Hari Terakhir": "Last 7 Days Sales",')
        html = html.replace('"Pintasan Cepat": "Pintasan Cepat",', '"Pintasan Cepat": "Pintasan Cepat", "Penjualan 7 Hari Terakhir": "Penjualan 7 Hari Terakhir",')
        print("Added i18n for chart title")

    with open('www/index.html', 'w', encoding='utf-8') as f:
        f.write(html)

if __name__ == '__main__':
    main()
